# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180115_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliconfig',
            name='PayAccount',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='支付账号'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='CommType',
            field=models.CharField(default='', max_length=200, verbose_name='商品信息'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='StoreId',
            field=models.CharField(default='', max_length=200, verbose_name='所属店铺'),
        ),
    ]
