# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180503_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliconfig',
            name='PayName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='收款姓名'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='PayAccount',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='收款账号'),
        ),
    ]
